// *****************************************************************************
// File generated by STM32 Imager 1.0
// Image name : ImageSTLogo
// Coding : 16bpp mode RGB565
// Source file : STLogo240.bmp
// *****************************************************************************


#ifndef __MAIN_IMAGESTLOGO_H
#define __MAIN_IMAGESTLOGO_H

#ifdef __cplusplus
 extern "C" {
#endif

#include "bsp.h"
	 
#define ImageSTLogo_height 180
#define ImageSTLogo_width 240
#define ImageSTLogo_bpp 4

extern const uint32_t ImageSTLogo[21600];

#ifdef __cplusplus
}
#endif

#endif  /* __MAIN_IMAGESTLOGO_H */
/*************************** End of file ****************************/

