// *****************************************************************************
// File generated by STM32 Imager 1.0
// Image name : ImageRGB888
// Coding : 24bpp mode
// Source file : RS986_photofinale-240x320.bmp
// *****************************************************************************
#ifndef __IMAGERGB888_H
#define __IMAGERGB888_H

#ifdef __cplusplus
 extern "C" {
#endif

#include "bsp.h"
	 
#define ImageRGB888_height 320
#define ImageRGB888_width 240
#define ImageRGB888_bpp 5

extern const uint32_t ImageRGB888[57600];
	 
#ifdef __cplusplus
}
#endif

#endif /* __IMAGERGB888_H */	 
